### PR TITLE
avoid double escaped entities in labels

### PR DESCRIPTION
**Pull request by becoded**
Labels for multicheckboxes are double escaped. 
Avoid this from happening.

### CODE REVIEW

**Review by neilime — APPROVED** [review]
LGTM

**Comment by neilime** [comment]
Thank you for your contribution @becoded

**Comment by becoded** [comment]
You're welcome!
Any idea when you will release a new version so this can be pulled in using composer?

**Comment by neilime** [comment]
Here it is: https://github.com/neilime/twbs-helper-module/releases/tag/v5.4.1

**Pull request merged**
