### PR TITLE
Include module activation in installation.md

### PR DESCRIPTION
**Pull request by modir**
The most important part is missing in the documentation. Loading the module. Just by the rest of the documentation it is not clear what the module name. So this helps a lot.

### CODE REVIEW

**Comment by froschdesign** [comment]
> The most important part is missing in the documentation.

This is done automatically when the component installer is used. See the laminas-cache documentation as an example: https://docs.laminas.dev/laminas-cache/v3/installation/#installation-for-mezzio-and-laminas-mvc-application

https://github.com/neilime/twbs-helper-module/blob/908351e48d175c810358c6b2c09028129bf1e7f5/composer.json#L84-L92

**Comment by modir** [comment]
I had here several Zend projects which I migrated to Laminas. For all of them I removed the old Zend version of this library and then added the new one as described on this page. And in none of the cases it was automatically added. And I guess many will migrate like I do. So definitely there should be a comment in one way or another.

**Comment by modir** [comment]
> I suggest both options, as described in the official documentation.

I guess by "official documentation" you mean the laminas-cache link and not the official twbs-helper-module documentation? We could do it similar as well. @neilime How do you want to have it? I can then make another adjustment.

**Comment by froschdesign** [comment]
> And in none of the cases it was automatically added.

Make sure [laminas-component-installer](https://docs.laminas.dev/laminas-component-installer/) and then Composer jumps in.

> I guess by "official documentation" you mean the laminas-cache link and not the official twbs-helper-module documentation?

Correct.

**Pull request closed without merging**
